Verbose: True
catalog_filenames:       "_20??.yaml"
Registration_Data:      "CTI Students.xlsx"
Completed_Courses_Data: "Student Records Information - Faculty Access Portal.xlsx"
Output_File:            "StudentsAudit.xlsx"
Number_Projection_Courses: 10
Number_Key_Courses:        3

Concentrations: { 
  "Security and Network Tech" : "SECNET",
  "Web and Mobile App Development" : "WAM",
  "Business Intelligence" : "BI",
  "Enterprise Systems" : "ES",
  "Mgmt. of Information Systems" : "MIS"
}

Equal_Catalog_Years: {
  "2017": "2019",
  "2018": "2019",
  "2022": "2021",
  "2023": "2021"
}

File_Format: {
  "CTI Students.xlsx": {
    skiprows: 0,
    columns: {
      "STUD_ID" : "ID",
      "GENDER" : "Gender",
      "CAMPUS" : "Campus",
      "CTLG_TERM" : "Catalog",
      "CONCENTRATION" : "Concentration",
      "SKILL" : "Skill",
      "CGPA" : "cGPA",
      "WF_W_SPRING_2024" : "Failed_Courses",
      "REG_CRSE_202421" : "Registered",
      "REG_CRSE_202323" : "Registered_Summer"
    }
  },
  "Student Records Information - Faculty Access Portal.xlsx": {
    skiprows: 2,
    columns: {
      "Student ID" : "ID",
      "CurrentCourses" : "CurrentCourses",
      "CompletedCourses" : "Completed_Courses",
    }
  }
}