Verbose:                    False
catalog_filenames:          "_20??.yaml"
catalog_defaults:           "_common_catalog.yaml"
Input_File:                 "Student Records Information - Faculty Access Portal.xlsx"
# Input_File:                 "CTI Students degree Audit.xlsx"
Audit_Output_File:          "StudentsAudit.xlsx"
Forecast_Output_File:       "StudentsForecast.xlsx"
# Registration_Data:          ""  # additional data for columns not in FAP: FailedCourses, Registered_Summer
Number_Projection_Courses:  10
Number_Key_Courses:         3

Concentrations: { 
  "Security and Network Tech" : "SECNET",
  "Security and Network Tech (_SN)" : "SECNET",
  "Web and Mobile App Development" : "WAM",
  "Web and Mobile App Development (_WM)" : "WAM",
  "Business Intelligence" : "BI",
  "Business Intelligence (_BI)": "BI",
  "Enterprise Systems" : "ES",
  "Enterprise Systems (_ES)" : "ES",
  "Mgmt. of Information Systems" : "MIS",
  "Mgmt. of Information Systems (_MS)" : "MIS",

  "Cyber Security SPZ (_CY)": "MS.CyberSecurity",
  "Information Technology (MINT)": "MS.DTI"
}

Equal_Catalog_Years: {
  "2017": "2019",
  "2018": "2019",
  "2022": "2021",
  "2023": "2021"
}

File_Format: {
  "Student Records Information - Faculty Access Portal.xlsx": {
    skiprows: 2,
    columns: {
      "Student ID" : "ID",
      "Admitted Term (Major)" : "Catalog",
      "NextCourses" : "Registered",
      "CGPA" : "cGPA"
    }
  }
}