Verbose: False
catalog_filenames:  "_20??.yaml"
Input_Data_File:    "Students.xlsx"
Output_Data_File:   "StudentsAudit.xlsx"

Concentrations: { "Security and Network Tech":      "SECNET",
                  "Web and Mobile App Development": "WAM",
                  "Business Intelligence":          "BI",
                  "Enterprise Systems":             "ES",
                  "Mgmt. of Information Systems":   "MIS"}

Equal_Catalog_Years: {"2017": "2019",
                      "2018": "2019",
                      "2022": "2021",
                      "2023": "2021" }

File_Format: {
  "Students.xlsx": {
#    sep: ",",
    skiprows: 0,
    columns: {
      "STUD_ID" : "ID",
      "STU_NAME" : "Name",
      "CTLG_TERM" : "Catalog",
      "MAJOR" : "Major",
      "CONCENTRATION" : "Concentration",
      "SKILL" : "Skill",
      "CGPA" : "cGPA",
      "EARNED_HRS" : "ECH",
      "ASTD" : "Standing",
      "WF_W_SPRING_2024" : "Failed_Courses",
      "REG_HRS_202421" : "Registered_CH",
      "COUNT_CRSE_202421" : "Registered_Count",
      "REG_CRSE_202421" : "Registered",
      "REG_CRSE_202323" : "Registered_Summer",
      "COUNT_CRSE_202323" : "Registered_Summer_Count",
      "REG_HRS_202323" : "Registered_Summer_CH",
      "CurrentCourses" : "Current_Courses",
      "CompletedCourses" : "Completed_Courses",
      "IncompleteCourses" : "Remaining_Courses"
    }
  }
}