Verbose:                    False
catalog_filenames:          "catalogs/20*.yaml"
catalog_defaults:           "catalogs/_common_catalog.yaml"
# Input_File:                 "Student Records Information - Faculty Access Portal.xlsx"
Input_File:                 "Student Records Information - Faculty Access Portal_Fatna.xlsx"
Audit_Output_File:          "StudentsAudit.xlsx"
Forecast_d_Output_File_sum: "StudentsForecast_d_summary.xlsx"  # summary of detailed forecast: Deterministic
Forecast_d_Output_File_det: "StudentsForecast_d_details.xlsx"  # detailed forecast: Deterministic
Forecast_s_Output_File_sum: "StudentsForecast_s_summary.xlsx"  # summary of detailed forecast: Stochastic
Forecast_s_Output_File_det: "StudentsForecast_s_details.xlsx"  # detailed forecast: Stochastic
# Registration_Data:          ""  # additional data for columns not in FAP: FailedCourses, Registered_Summer

Number_Projection_Courses:  10
Number_Key_Courses:         3
MaxLabs:                    2
MinimalEnrollmentMode:      True
GuessSubstitutions:         True
CH_ranges:                [ { gpa: [0.0, 1.9999], minCH: 11, maxCH: 13 },     # { gpa: [ minGPA, maxGPA ], minCH: CH maxCH: CH } for each group
                            { gpa: [2.0, 4.0000], minCH: 14, maxCH: 16 } ]    # use last entry as default when cGPA=0, EarnedHours=0, and FailedCourses=0

Allowed_Duplicate_Courses: [ GroupA, GroupD, GroupG, P_Elective, ZU_Elective ]

# Stochastic forecasting parameters
Perform_Stochastic_forecasting:       False
First_choice_ratio:                   0.75  # used in stochastic forecasting; the ratio of students who will register in their first choice courses (vs. second choice courses)
Excluded_from_stochastic_forecasting: [ CIT490, CIT499 ]  # used in stochastic forecasting; courses that should stick with deterministic forecasting

Concentrations: { 
  "Security and Network Tech" : "SECNET",
  "Security and Network Tech (_SN)" : "SECNET",
  "Web and Mobile App Development" : "WAM",
  "Web and Mobile App Development (_WM)" : "WAM",
  "Business Intelligence" : "BI",
  "Business Intelligence (_BI)": "BI",
  "Enterprise Systems" : "ES",
  "Enterprise Systems (_ES)" : "ES",
  "Mgmt. of Information Systems" : "MIS",
  "Mgmt. of Information Systems (_MS)" : "MIS",

  "Cyber Security SPZ (_CY)": "MS.CyberSecurity",
  "Information Technology (MINT)": "MS.DTI"
}

Equal_Catalog_Years: {
  "2017": "2019",
  "2018": "2019",
  "2022": "2021",
  "2023": "2021",
  "2025": "2024"
}

File_Format: {
  "Student Records Information - Faculty Access Portal_Fatna.xlsx": {
    skiprows: 2,
    columns: {
      "Student ID" : "ID",
      "Admitted Term (Major)" : "Catalog",
      "NextCourses" : "Registered",
      "CGPA" : "cGPA"
    }
  },
  "Student Records Information - Faculty Access Portal.xlsx": {
    skiprows: 2,
    columns: {
      "Student ID" : "ID",
      "Admitted Term (Major)" : "Catalog",
      "NextCourses" : "Registered",
      "CGPA" : "cGPA"
    }
  },
}